# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CordCloud Checkin Selenium

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10" 
    
    - name: Set up the virtual X server
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 180
        max_attempts: 3
        retry_on: error
        retry_wait_seconds: 30
        command: |
          sudo apt-get update
          sudo apt-get install xvfb
        
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Start checkin
      env: 
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        URL: ${{secrets.URL}}
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        jobs -l
        python AutoCheckin.py --username=$USERNAME --password=$PASSWORD --url=$URL

